CREATE TABLE IF NOT EXISTS interactions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    rating FLOAT NOT NULL,
    timestamp TIMESTAMP WITH THE ZONE NOT NULL,
    UNIQUE (user_id, event_id)
);

CREATE TABLE IF NOT EXISTS similarities (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    eventA BIGINT NOT NULL,
    eventB BIGINT NOT NULL,
    similarity FLOAT NOT NULL,
    timestamp TIMESTAMP WITH THE ZONE NOT NULL,
    UNIQUE (eventA, eventB)
)