spring:
  application:
    name: aggregator
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
      discovery:
        enabled: false
        service-id: config-server

  profiles:
    active: default

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
---
spring:
  config:
    activate:
      on-profile: default
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
