server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: event-service
    leaseRenewalIntervalInSeconds: 10
management:
  endpoints:
    web:
      exposure:
        include: health,info
spring:
  datasource:
    url: jdbc:postgresql://event-db:5432/event-db
    username: event_user
    password: event_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
grpc:
  client:
    userActionControllerGrpcClient:
      address: 'discovery:///collector'
      negotiationType: PLAINTEXT
      metadata:
        portKey: gRPC.port
    analyzerGrpcClient:
      address: 'discovery:///analyzer'
      negotiationType: PLAINTEXT
      metadata:
        portKey: gRPC.port

gateway:
  url: http://infra-gateway:8080