networks:
  ewm-net:

services:
  discovery-server:
    build: infra/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - ewm-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery-server:8761/eureka/apps"]
      timeout: 5s
      interval: 10s
      retries: 12

  config-server:
    build: infra/config-server
    container_name: config-server
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=9091
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config-server:9091/actuator/health"]
      timeout: 5s
      interval: 15s
      retries: 10

  gateway-server:
    build: infra/gateway-server
    container_name: gateway-server
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/

  event-db:
    image: postgres:16.1
    container_name: postgres-ewm-event-db
    networks:
      - ewm-net
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ewm-event
    ports:
      - 5434:5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      timeout: 5s
      interval: 10s
      retries: 15

  event-service:
    build: core/event-service
    container_name: event-service
    depends_on:
      event-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://event-db:5432/ewm-event
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      timeout: 5s
      interval: 15s
      retries: 10

  request-db:
    image: postgres:16.1
    container_name: postgres-ewm-request-db
    networks:
      - ewm-net
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ewm-request
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      timeout: 5s
      interval: 10s
      retries: 15

  request-service:
    build: core/request-service
    container_name: ewm-request-service
    depends_on:
      request-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://request-db:5432/ewm-request
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      timeout: 5s
      interval: 15s
      retries: 10

  user-db:
    image: postgres:16.1
    container_name: postgres-ewm-user-db
    networks:
      - ewm-net
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ewm-user
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      timeout: 5s
      interval: 10s
      retries: 15

  user-service:
    build: core/user-service
    container_name: ewm-user-service
    depends_on:
      user-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/ewm-user
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      timeout: 5s
      interval: 15s
      retries: 10

  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9101:9101"
    networks:
      - ewm-net
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker, controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      - kafka
    networks:
      - ewm-net
    command: >
      bash -c "
      sleep 10 &&
      kafka-topics --create --topic stats.user-actions.v1 \
                   --partitions 1 --replication-factor 1 --if-not-exists \
                   --bootstrap-server kafka:29092 &&
      kafka-topics --create --topic stats.events-similarity.v1 \
                   --partitions 1 --replication-factor 1 --if-not-exists \
                   --bootstrap-server kafka:29092
      "
    init: true

  collector:
    build: stats/collector
    container_name: ewm-collector
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health"]
      timeout: 5s
      interval: 15s
      retries: 10

  aggregator:
    build: stats/aggregator
    container_name: ewm-aggregator
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - SPRING_APPLICATION_NAME=aggregator
      - SPRING_CLOUD_CONFIG_ENABLED=false
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_HOSTNAME=ewm-aggregator
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:29092
      - KAFKA_AGGREGATOR_CONSUMER_TOPIC=stats.user-actions.v1
      - KAFKA_AGGREGATOR_PRODUCER_TOPIC=stats.events-similarity.v1
      - LOGGING_LEVEL_COM_NETFLIX_DISCOVERY=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_NETFLIX_EUREKA=DEBUG

  analyzer-db:
    image: postgres:16.1
    container_name: postgres-ewm-analyzer-db
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ewm-analyzer
    networks:
      - ewm-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      timeout: 5s
      interval: 10s
      retries: 15

  analyzer:
    build: stats/analyzer
    container_name: ewm-analyzer
    depends_on:
      analyzer-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://analyzer-db:5432/ewm-analyzer
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8087/actuator/health"]
      timeout: 5s
      interval: 15s
      retries: 10