networks:
  ewm-net:
    name: ewm-net

services:
  discovery-server:
    build: infra/discovery-server
    container_name: infra-discovery
    ports:
      - "8761:8761"
    networks:
      - ewm-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://discovery-server:8761/eureka/apps" ]
      timeout: 5s
      interval: 10s
      retries: 12

  config-server:
    build: infra/config-server
    container_name: infra-config
    depends_on:
      - discovery-server
    networks:
      - ewm-net
    environment:
      - SERVER_PORT=8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-server:8888/actuator/health" ]
      timeout: 5s
      interval: 15s
      retries: 10

  gateway-server:
    build: infra/gateway-server
    container_name: infra-gateway
    ports:
      - "8080:8080"
    depends_on:
      - config-server
    networks:
      - ewm-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - SERVER_PORT=8080
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      timeout: 5s
      interval: 15s
      retries: 10

  event-db:
    image: postgres:16.1
    container_name: db-event
    networks:
      - ewm-net
    environment:
      - POSTGRES_PASSWORD=event_password
      - POSTGRES_USER=event_user
      - POSTGRES_DB=event-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      timeout: 5s
      interval: 10s
      retries: 15

  request-db:
    image: postgres:16.1
    container_name: db-request
    networks:
      - ewm-net
    environment:
      - POSTGRES_PASSWORD=request_password
      - POSTGRES_USER=request_user
      - POSTGRES_DB=request-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      timeout: 5s
      interval: 10s
      retries: 15

  user-db:
    image: postgres:16.1
    container_name: db-user
    networks:
      - ewm-net
    environment:
      - POSTGRES_PASSWORD=user_password
      - POSTGRES_USER=user_user
      - POSTGRES_DB=user-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      timeout: 5s
      interval: 10s
      retries: 15

  compilation-db:
    image: postgres:16.1
    container_name: compilation-db
    networks:
      - ewm-net
    environment:
      - POSTGRES_PASSWORD=compilation_password
      - POSTGRES_USER=compilation_user
      - POSTGRES_DB=compilation-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      timeout: 5s
      interval: 10s
      retries: 15

  category-db:
    image: postgres:16.1
    container_name: db-category
    networks:
      - ewm-net
    environment:
      - POSTGRES_PASSWORD=category_password
      - POSTGRES_USER=category_user
      - POSTGRES_DB=category-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      timeout: 5s
      interval: 10s
      retries: 15

  comment-db:
    image: postgres:16.1
    container_name: db-comment
    networks:
      - ewm-net
    environment:
      - POSTGRES_PASSWORD=comment_password
      - POSTGRES_USER=comment_user
      - POSTGRES_DB=comment-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      timeout: 5s
      interval: 10s
      retries: 15

  analyzer-db:
    image: postgres:16.1
    container_name: db-analyzer
    networks:
      - ewm-net
    environment:
      - POSTGRES_PASSWORD=analyzer_password
      - POSTGRES_USER=analyzer_user
      - POSTGRES_DB=analyzer-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      timeout: 5s
      interval: 10s
      retries: 15

  event-service:
    build: core/event-service
    container_name: core-event
    depends_on:
      - event-db
      - config-server
      - discovery-server
    networks:
      - ewm-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - DB_HOST=event-db
      - DB_PORT=5432
      - DB_NAME=event-db
      - DB_USER=event_user
      - DB_PASSWORD=event_password
      - SERVER_PORT=8081
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  request-service:
    build: core/request-service
    container_name: core-request
    depends_on:
      - request-db
      - config-server
      - discovery-server
    networks:
      - ewm-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://request-db:5432/request-db
      - SPRING_DATASOURCE_USERNAME=request_user
      - SPRING_DATASOURCE_PASSWORD=request_password
      - SERVER_PORT=8082
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  user-service:
    build: core/user-service
    container_name: core-user
    depends_on:
      - user-db
      - config-server
      - discovery-server
    networks:
      - ewm-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user-db
      - SPRING_DATASOURCE_USERNAME=user_user
      - SPRING_DATASOURCE_PASSWORD=user_password
      - SERVER_PORT=8083
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  compilation-service:
    build: core/compilation-service
    container_name: core-compilation
    depends_on:
      - compilation-db
      - config-server
      - discovery-server
    networks:
      - ewm-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - SPRING_APPLICATION_NAME=compilation-service
      - SPRING_DATASOURCE_URL=jdbc:postgresql://compilation-db:5432/compilation-db
      - SPRING_DATASOURCE_USERNAME=compilation_user
      - SPRING_DATASOURCE_PASSWORD=compilation_password
      - SERVER_PORT=8084
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  category-service:
    build: core/category-service
    container_name: core-category
    depends_on:
      - category-db
      - config-server
      - discovery-server
    networks:
      - ewm-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - SPRING_APPLICATION_NAME=category-service
      - SPRING_DATASOURCE_URL=jdbc:postgresql://category-db:5432/category-db
      - SPRING_DATASOURCE_USERNAME=category_user
      - SPRING_DATASOURCE_PASSWORD=category_password
      - SERVER_PORT=8086
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  comment-service:
    build: core/comment-service
    container_name: core-comment
    depends_on:
      - comment-db
      - config-server
      - discovery-server
    networks:
      - ewm-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - SPRING_APPLICATION_NAME=comment-service
      - SPRING_DATASOURCE_URL=jdbc:postgresql://comment-db:5432/comment-db
      - SPRING_DATASOURCE_USERNAME=comment_user
      - SPRING_DATASOURCE_PASSWORD=comment_password
      - SERVER_PORT=8085
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8085/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - ewm-net
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      CLUSTER_ID: K0EA9p0yEe6MkAAAAkKsEg

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      - kafka
    networks:
      - ewm-net
    command: bash -c "sleep 10 && kafka-topics --create --topic stats.user-actions.v1 --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server kafka:29092 && kafka-topics --create --topic stats.events-similarity.v1 --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server kafka:29092"
    init: true

  collector:
    build: stats/collector
    container_name: stats-collector
    depends_on:
      - config-server
      - discovery-server
      - kafka
    networks:
      - ewm-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - GRPC_SERVER_PORT=19336
      - SERVER_PORT=8087
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8087/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  aggregator:
    build: stats/aggregator
    container_name: stats-aggregator
    depends_on:
      - config-server
      - discovery-server
      - kafka
    networks:
      - ewm-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_HOSTNAME=ewm-aggregator
      - LOGGING_LEVEL_COM_NETFLIX_DISCOVERY=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_NETFLIX_EUREKA=DEBUG
      - SERVER_PORT=8088
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8088/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  analyzer:
    build: stats/analyzer
    container_name: stats-analyzer
    depends_on:
      - analyzer-db
      - config-server
      - discovery-server
    networks:
      - ewm-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - GRPC_SERVER_PORT=19337
      - SPRING_APPLICATION_NAME=stats.service.dashboard
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_DATASOURCE_URL=jdbc:postgresql://analyzer-db:5432/analyzer-db
      - SPRING_DATASOURCE_USERNAME=analyzer_user
      - SPRING_DATASOURCE_PASSWORD=analyzer_password
      - SERVER_PORT=8089
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8089/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s