eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0

stats:
  baseUrl: http://stats-server

# Основные поля
kafka_aggregator:
  bootstrap-servers: localhost:9092

  # Вложенный класс Consumer
  consumer:
    group-id: my-group
    topic: stats.events-similarity.v1, stats.user-actions.v1
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  # Вложенный класс Producer
  producer:
    topic: output-topic
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer

