eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10

server:
  port: 0

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: aggregator-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: malyshev.egor.deserialization.UserActionAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: malyshev.egor.serialization.AvroSerializer
  cloud:
    inetutils:
      preferred-networks:
        - 172.

kafka-aggregator:
  consumer:
    topic: stats.user-actions.v1
  producer:
    topic: stats.events-similarity.v1