server:
  port: 8086
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: category-service
    leaseRenewalIntervalInSeconds: 10
management:
  endpoints:
    web:
      exposure:
        include: health,info
spring:
  datasource:
    url: jdbc:postgresql://category-db:5432/category-db
    username: category_user
    password: category_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

gateway:
  url: http://gateway-server:8080