management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
  endpoint:
    gateway:
      enabled: true

resilience4j:
  timeLimiter:
    instances:
      myCircuitBreaker:
        timeout-duration: 30s
  circuitBreaker:
    instances:
      myCircuitBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
spring:
  cloud:
    gateway:
      default-filters:
        - CircuitBreaker=myCircuitBreaker
      routes:
        # Category
        - id: category_service_route
          uri: lb://category-service
          predicates:
            - Path=/categories,/categories/{categoryId},/admin/categories,/admin/categories/{categoryId}

        # Comment
        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/admin/events/{eventId}/comments,/admin/events/{eventId}/comments/{commentId},/users/{userId}/events/{eventId}/comments,/users/{userId}/events/{eventId}/comments/{commentId},/events/{eventId}/comments

        # Compilation
        - id: compilation_service_route
          uri: lb://compilation-service
          predicates:
            - Path=/admin/compilations,/admin/compilations/{compilationId},/compilations,/compilations/{compilationId}

        # Event
        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/events,/events/{eventId},/admin/events,/admin/events/{eventId},/users/{userId}/events,/users/{userId}/events/{eventId},/admin/events/by-ids,/admin/events/exists-by-categoryId/{categoryId}

        # Request
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/events/{eventId}/requests,/users/{userId}/requests,/users/{userId}/requests/{requestId}/cancel,/events/{eventId}/requests/confirmed

        # User
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users,/admin/users/{userId}

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG