server:
  port: 8085
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: comment-service
    leaseRenewalIntervalInSeconds: 10
management:
  endpoints:
    web:
      exposure:
        include: health,info
spring:
  datasource:
    url: jdbc:postgresql://comment-db:5432/comment-db
    username: comment_user
    password: comment_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
feign:
  client:
    config:
      private-request-service:
        loggerLevel: full

gateway:
  url: http://gateway-server:8080